buildscript {
    repositories {
        //TODO! Del this
        mavenLocal()

        mavenCentral()
    }

    dependencies {
        classpath 'info.gianlucacosta.aurora:aurora:10.0.0-SNAPSHOT'
    }
}


apply plugin: 'scala'
apply plugin: 'application'
apply plugin: 'info.gianlucacosta.aurora'


group = 'info.gianlucacosta.graphsj'
archivesBaseName = 'graphsj'
version = '7.0.0-SNAPSHOT'

description = 'ScalaFX didactic application for graph algorithms'

mainClassName = "info.gianlucacosta.graphsj.App"

aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }
}


dependencies {
    compile 'org.scala-lang:scala-library:2.11.8'

    compile 'org.scala-lang:scala-xml:2.11.0-M4'
    compile 'com.thoughtworks.xstream:xstream:1.4.8'
    compile 'org.reflections:reflections:0.9.10'
    compile 'javax.json:javax.json-api:1.0'
    compile 'org.glassfish:javax.json:1.0.4'

    compile 'info.gianlucacosta.graphsj:graphsj-sdk:7.0.0-SNAPSHOT'
}